# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcad7558cb1c6a01ef1c316ca3b3d734240bf4a5b66c7055bbe7652b4a5a85e2c5ae88c0a02c761899e68f9be4f59b97265475a3b86e2006115bf22184c63249

test:
  secret_key_base: 7e8e9b57c91074306c3323cc466c97b0390d4eb387e8bef23148d60a254ae0d2e336d232bc5339b59b15827a1f398145d7a4f16743504336e1997f2c536da8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
